/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import static java.awt.Frame.MAXIMIZED_BOTH;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;

/**
 *
 * @author Moi
 */
public class MDIApplication extends javax.swing.JFrame {

    /**
     * Creates new form MDIApplication
     */
    private static MDIApplication instance;

    public MDIApplication() {
        initComponents();
        this.setTitle("Gestion des supports pedagogiques");
        setExtendedState(MAXIMIZED_BOTH);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

    }

    public static MDIApplication getInstance() {
        if (instance == null) {
            instance = new MDIApplication();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        supportMenuItem = new javax.swing.JMenuItem();
        professeurMenuItem = new javax.swing.JMenuItem();
        ajoutsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        supportpartitreMenuItem = new javax.swing.JMenuItem();
        supportParProfesseurMenuItem = new javax.swing.JMenuItem();
        supportParTypeMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo-removebg-preview.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        desktopPane.add(jLabel2);
        jLabel2.setBounds(0, 10, 440, 100);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Gestion");

        supportMenuItem.setMnemonic('o');
        supportMenuItem.setText("Support");
        supportMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supportMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(supportMenuItem);

        professeurMenuItem.setMnemonic('s');
        professeurMenuItem.setText("Professeur");
        professeurMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                professeurMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(professeurMenuItem);

        ajoutsMenuItem.setMnemonic('a');
        ajoutsMenuItem.setText("Ajouts");
        ajoutsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutsMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(ajoutsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Recherche");

        supportpartitreMenuItem.setMnemonic('t');
        supportpartitreMenuItem.setText("Rechercher un support par titre");
        supportpartitreMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supportpartitreMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(supportpartitreMenuItem);

        supportParProfesseurMenuItem.setMnemonic('y');
        supportParProfesseurMenuItem.setText("Filtrer les supports par professeur");
        supportParProfesseurMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supportParProfesseurMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(supportParProfesseurMenuItem);

        supportParTypeMenuItem.setText("Lister les supports par type");
        supportParTypeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supportParTypeMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(supportParTypeMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Statistiques");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Nombre de supports par professeur ");
        contentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(contentMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void professeurMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_professeurMenuItemActionPerformed
        closeAllInternalFrames();
        ProfesseurForm pf = new ProfesseurForm();
        desktopPane.add(pf);
        pf.setVisible(true);
        centerInternalFrame(pf);
    }//GEN-LAST:event_professeurMenuItemActionPerformed

    private void supportMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supportMenuItemActionPerformed
        closeAllInternalFrames();
        SupportForm ss = new SupportForm();
        desktopPane.add(ss);
        ss.setVisible(true);
        centerInternalFrame(ss);
    }//GEN-LAST:event_supportMenuItemActionPerformed

    private void ajoutsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutsMenuItemActionPerformed
        closeAllInternalFrames();
        AjoutSupportForm asf = new AjoutSupportForm();
        desktopPane.add(asf);
        asf.setVisible(true);
        centerInternalFrame(asf);
    }//GEN-LAST:event_ajoutsMenuItemActionPerformed

    private void closeAllInternalFrames() {
        for (JInternalFrame frame : desktopPane.getAllFrames()) {
            frame.dispose();
        }
    }

    private void centerInternalFrame(JInternalFrame internalFrame) {
        int x = (desktopPane.getWidth() - internalFrame.getWidth()) / 2;
        int y = (desktopPane.getHeight() - internalFrame.getHeight()) / 2;
        internalFrame.setLocation(x, y);
    }

    private void supportpartitreMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supportpartitreMenuItemActionPerformed
        closeAllInternalFrames();
        SupportParTitre spt = new SupportParTitre();
        desktopPane.add(spt);
        spt.setVisible(true);
        centerInternalFrame(spt);
    }//GEN-LAST:event_supportpartitreMenuItemActionPerformed

    private void supportParProfesseurMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supportParProfesseurMenuItemActionPerformed
        closeAllInternalFrames();
        SupportParProfesseur spp = new SupportParProfesseur();
        desktopPane.add(spp);
        spp.setVisible(true);
        centerInternalFrame(spp);
    }//GEN-LAST:event_supportParProfesseurMenuItemActionPerformed

    private void supportParTypeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supportParTypeMenuItemActionPerformed
        closeAllInternalFrames();
        SupportParType spt = new SupportParType();
        desktopPane.add(spt);
        spt.setVisible(true);
        centerInternalFrame(spt);
    }//GEN-LAST:event_supportParTypeMenuItemActionPerformed

    private void contentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentMenuItemActionPerformed
        closeAllInternalFrames();
        BarChart bs = new BarChart();
        desktopPane.add(bs);
        bs.setVisible(true);
        centerInternalFrame(bs);
    }//GEN-LAST:event_contentMenuItemActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDIApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ajoutsMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem professeurMenuItem;
    private javax.swing.JMenuItem supportMenuItem;
    private javax.swing.JMenuItem supportParProfesseurMenuItem;
    private javax.swing.JMenuItem supportParTypeMenuItem;
    private javax.swing.JMenuItem supportpartitreMenuItem;
    // End of variables declaration//GEN-END:variables

}
