/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import beans.Etype;
import beans.Support;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import services.SupportService;

/**
 *
 * @author Moi
 */
public class SupportForm extends javax.swing.JInternalFrame {

    private SupportService ss;
    private DefaultTableModel model;
    private static int id;

    /**
     * Creates new form SupportForm
     */
    public SupportForm() {
        initComponents();
        this.setTitle("Gestion des supports ");
        ss = new SupportService();
        model = (DefaultTableModel) ListeSupports.getModel();
        load();
    }

    public void load() {
        model.setRowCount(0);
        for (Support s : ss.findAll()) {
            model.addRow(new Object[]{s.getId(), s.getTitre(), s.getType(), s.getFichier()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTitre = new javax.swing.JTextField();
        txtFichier = new javax.swing.JTextField();
        bnAdd = new javax.swing.JButton();
        pdf = new javax.swing.JRadioButton();
        presentation = new javax.swing.JRadioButton();
        lienweb = new javax.swing.JRadioButton();
        bnDelete = new javax.swing.JButton();
        bnUpdate = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListeSupports = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gestion et affichage des supports");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gestion des supports", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("Titre : ");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Type :");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Fichier :");

        bnAdd.setBackground(new java.awt.Color(153, 153, 255));
        bnAdd.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        bnAdd.setForeground(new java.awt.Color(51, 102, 255));
        bnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addicon.jpg"))); // NOI18N
        bnAdd.setText("Ajouter");
        bnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnAddActionPerformed(evt);
            }
        });

        buttonGroup1.add(pdf);
        pdf.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        pdf.setText("PDF");

        buttonGroup1.add(presentation);
        presentation.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        presentation.setText("Presentation");

        buttonGroup1.add(lienweb);
        lienweb.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        lienweb.setText("Lien_Web");

        bnDelete.setBackground(new java.awt.Color(153, 153, 255));
        bnDelete.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        bnDelete.setForeground(new java.awt.Color(204, 0, 51));
        bnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/deleteicon.jpg"))); // NOI18N
        bnDelete.setText("Supprimer");
        bnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnDeleteActionPerformed(evt);
            }
        });

        bnUpdate.setBackground(new java.awt.Color(153, 153, 255));
        bnUpdate.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        bnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/updateicon.jpg"))); // NOI18N
        bnUpdate.setText("Modifier");
        bnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnUpdateActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ressourcesicon.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(pdf)
                        .addGap(18, 18, 18)
                        .addComponent(presentation)
                        .addGap(18, 18, 18)
                        .addComponent(lienweb)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTitre, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(txtFichier))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bnDelete)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTitre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pdf)
                    .addComponent(presentation)
                    .addComponent(lienweb))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtFichier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(bnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bnDelete))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Liste des supports", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        ListeSupports.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        ListeSupports.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Titre", "Type", "Fichier"
            }
        ));
        ListeSupports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListeSupportsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ListeSupports);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(217, 217, 217))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnAddActionPerformed
        String titre = txtTitre.getText().toString();
        Etype type = null;
        String fichier = txtFichier.getText().toString();

        if (pdf.isSelected()) {
            type = Etype.PDF;
        } else if (presentation.isSelected()) {
            type = Etype.PRESENTATION;
        } else {
            type = Etype.LIEN_WEB;
        }

        if (ss.create(new Support(titre, type, fichier))) {
            JOptionPane.showMessageDialog(this, "Support ajouté avec succès");
            load();
        } else {
            JOptionPane.showMessageDialog(this, "Erreur lors de l'ajout");

        }


    }//GEN-LAST:event_bnAddActionPerformed

    private void bnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnDeleteActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(this, "Voulez vous vraiment supprimer ce support?");
        if (response == 0) {
            ss.delete(ss.findById(id));
            load();
        }
    }//GEN-LAST:event_bnDeleteActionPerformed

    private void ListeSupportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListeSupportsMouseClicked
        // TODO add your handling code here:
        id = Integer.parseInt(model.getValueAt(ListeSupports.getSelectedRow(), 0).toString());
        txtTitre.setText(model.getValueAt(ListeSupports.getSelectedRow(), 1).toString());
        String typeStr = model.getValueAt(ListeSupports.getSelectedRow(), 2).toString();

        if (typeStr.equals("PDF")) {
            pdf.setSelected(true);
            presentation.setSelected(false);
            lienweb.setSelected(false);
        } else if (typeStr.equals("PRESENTATION")) {
            pdf.setSelected(false);
            presentation.setSelected(true);
            lienweb.setSelected(false);
        } else {
            pdf.setSelected(false);
            presentation.setSelected(false);
            lienweb.setSelected(true);
        }
        txtFichier.setText(model.getValueAt(ListeSupports.getSelectedRow(), 3).toString());

    }//GEN-LAST:event_ListeSupportsMouseClicked

    private void bnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnUpdateActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "Voulez vous vraiment modifier ce support?");
        if (response == 0) {
            String titre = txtTitre.getText().toString();
            Etype type = null;
            String fichier = txtFichier.getText().toString();

            if (pdf.isSelected()) {
                type = Etype.PDF;
            } else if (presentation.isSelected()) {
                type = Etype.PRESENTATION;
            } else {
                type = Etype.LIEN_WEB;
            }

            if (ss.update(new Support(id, titre, type, fichier))) {
                JOptionPane.showMessageDialog(this, "Support modifié avec succès");
                load();
            } else {
                JOptionPane.showMessageDialog(this, "Erreur lors de l'ajout");

            }

        }
    }//GEN-LAST:event_bnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ListeSupports;
    private javax.swing.JButton bnAdd;
    private javax.swing.JButton bnDelete;
    private javax.swing.JButton bnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton lienweb;
    private javax.swing.JRadioButton pdf;
    private javax.swing.JRadioButton presentation;
    private javax.swing.JTextField txtFichier;
    private javax.swing.JTextField txtTitre;
    // End of variables declaration//GEN-END:variables
}
